---
name: "Acceptance Testing"

on: 
  push:
    branches:
      - "*"

jobs:
  get-matrix:
    name: Get Matrix from JSON
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Matrix
        id: matrix
        uses: Surnet/get-json-matrix@v1
        with:
          filepath: ./test_matrix.json

  acceptance:
    name: "Acceptance tests (${{matrix.platform.label}}, ${{matrix.collection}})"
    needs:
      - get-matrix
    if: ${{ needs.get-matrix.outputs.matrix != '{}' }}

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.get-matrix.outputs.matrix)}}

    env:
      PUPPET_GEM_VERSION: '~> 7.24'
      FACTER_GEM_VERSION: 'https://github.com/puppetlabs/facter#main'

    steps:
    - name: Print matrix
      run: |
        echo "${{matrix.platform}}"

    - name: Checkout Source
      uses: actions/checkout@v3

    - name: Activate Ruby 2.7
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "2.7"
        bundler-cache: true

    - name: Print bundle environment
      run: |
        echo ::group::bundler environment
        bundle env
        echo ::endgroup::

    - name: Create the fixtures directory
      run: |
        bundle exec rake spec_prep

    - name: check vars
      run: |
        export

    - name: Provision test environment
      run: |
        # bundle exec rake "litmus:provision_list[docker]"
        bundle exec rake "litmus:provision[${{matrix.platform.provider}},${{ matrix.platform.image }}]"
        FILE='spec/fixtures/litmus_inventory.yaml'
        sed -e 's/password: .*/password: "[redacted]"/' < $FILE || true

    - name: Install Agents and module
      run: |
        bundle exec rake 'litmus:install_agent[${{ matrix.collection }}]'
        bundle exec rake litmus:install_module

    - name: Run integration tests
      run: |
        bundle exec rake litmus:acceptance:parallel

    - name: Remove test environment
      if: ${{ always() }}
      continue-on-error: true
      run: |
        ls -lh ./spec/fixtures/
        cat ./spec/fixtures/litmus_inventory.yaml
        bundle exec rake 'litmus:tear_down'
