---
name: "Acceptance Testing"

on: 
  push:
    branches:
      - "*"

jobs:
  setup_matrix:
    name: "Setup Test Matrix"
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get-matrix.outputs.matrix }}

    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
      if: ${{ github.repository_owner == 'jortencio' }}

    - name: Activate Ruby 2.7
      uses: ruby/setup-ruby@v1
      if: ${{ github.repository_owner == 'jortencio' }}
      with:
        ruby-version: "2.7"
        bundler-cache: true

    - name: Print bundle environment
      if: ${{ github.repository_owner == 'jortencio' }}
      run: |
        echo ::group::bundler environment
        bundle env
        echo ::endgroup::

    - name: Setup Acceptance Test Matrix
      id: get-matrix
      run: |
        echo "matrix=$(cat test_matrix.json)" >> $GITHUB_OUTPUT


  acceptance:
    name: "Acceptance tests (${{matrix.platform.label}}, ${{matrix.puppet_agent}})"
    needs:
      - setup_matrix
    if: ${{ needs.setup_matrix.outputs.matrix != '{}' }}

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.setup_matrix.outputs.matrix)}}

    env:
      PUPPET_GEM_VERSION: '~> 7.24'
      FACTER_GEM_VERSION: 'https://github.com/puppetlabs/facter#main'

    steps:
    - name: Checkout Source
      uses: actions/checkout@v3

    - name: Activate Ruby 2.7
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "2.7"
        bundler-cache: true

    - name: Print bundle environment
      run: |
        echo ::group::bundler environment
        bundle env
        echo ::endgroup::

    - name: Create the fixtures directory
      run: |
        bundle exec rake spec_prep

    - name: check vars
      run: |
        export

    - name: Provision test environment
      run: |
        # bundle exec rake "litmus:provision_list[docker]"
        bundle exec rake "litmus:provision[${{matrix.platform.provider}},${{ matrix.platform.image }}]"
        FILE='spec/fixtures/litmus_inventory.yaml'
        sed -e 's/password: .*/password: "[redacted]"/' < $FILE || true

    - name: Install Agents and module
      run: |
        bundle exec rake 'litmus:install_agent[${{ matrix.puppet_agent }}]'
        bundle exec rake litmus:install_module

    - name: Run integration tests
      run: |
        bundle exec rake litmus:acceptance:parallel

    - name: Remove test environment
      if: ${{ always() }}
      continue-on-error: true
      run: |
        ls -lh ./spec/fixtures/
        cat ./spec/fixtures/litmus_inventory.yaml
        bundle exec rake 'litmus:tear_down'
